from fastapi import APIRouter, Depends, HTTPException
from uav_api.vehicles.copter import Copter
from uav_api.classes.responses import (
    COMMAND_FAILED,
    error_responses,
    BatteryInfoResponse,
    CompassTelemetryResponse,
    ErrorInfoResponse,
    GeneralTelemetryResponse,
    GpsTelemetryResponse,
    HomeInfoResponse,
    NedTelemetryResponse,
    RawGpsTelemetryResponse,
    SensorStatusResponse,
    SysStatusResponse,
)
from uav_api.routers.dependencies import get_copter_instance, get_args
from argparse import Namespace
router = APIRouter(
    prefix="/telemetry",
    tags=["telemetry"],
)

@router.get("/general", tags=["telemetry"], summary="Returns Copter general information such as velocities, heading, throttle percentage and altitude", response_model=GeneralTelemetryResponse, responses=COMMAND_FAILED)
def general_info(uav: Copter = Depends(get_copter_instance), args: Namespace = Depends(get_args)):
    """Sourced from the VFR_HUD MAVLink message: speeds in m/s, heading in
    degrees, throttle in percent, altitude in meters (MSL)."""
    try:
        info = uav.get_general_info()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_GENERAL_INFO FAIL: {e}")
    return {
        "device": "uav",
        "id": str(args.sysid),
        "result": "success",
        "info": {
            "airspeed": info.airspeed,
            "groundspeed": info.groundspeed,
            "heading": info.heading,
            "throttle": info.throttle,
            "alt": info.alt
        }
    }

@router.get("/gps", tags=["telemetry"], summary="Returns the copter current GPS information (the information provided by this endpoint is generated by the fusion of multiple sensor data such as GPS and accelerometers)", response_model=GpsTelemetryResponse, responses=COMMAND_FAILED)
def gps_info(uav: Copter = Depends(get_copter_instance), args: Namespace = Depends(get_args)):
    """Sourced from GLOBAL_POSITION_INT, converted to friendly units: lat/lon
    in degrees, altitudes in meters (relative_alt is above HOME), velocities in
    m/s, heading in degrees."""
    try:
        info = uav.get_gps_info()
        res_obj = {
            "device": "uav",
            "id": str(args.sysid),
            "result": "success", 
            "info": {
                "position": {
                    "lat": info.lat / 1.0e7, # to degrees
                    "lon": info.lon / 1.0e7, # to degrees
                    "alt": info.alt / 1000, # to meters
                    "relative_alt": info.relative_alt / 1000, # to meters
                },
                "velocity": {
                    "vx": info.vx / 100, # to meters per second
                    "vy": info.vy / 100, # to meters per second
                    "vz": info.vz / 100, # to meters per second
                },
                "heading": info.hdg / 100 # to degrees
            }
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_GPS_POSITION FAIL: {e}")
    return res_obj

@router.get("/gps_raw", tags=["telemetry"], summary="Returns the copter current raw GPS information (the information provided by this endpoint is generated directly by the GPS sensor)", response_model=RawGpsTelemetryResponse, responses=COMMAND_FAILED)
def gps_raw(uav: Copter = Depends(get_copter_instance), args: Namespace = Depends(get_args)):
    """Sourced from GPS_RAW_INT, converted to friendly units: lat/lon in
    degrees, altitude in meters, ground speed in m/s, course over ground in
    degrees. 'satelites' should be at least 6 before arming outdoors."""
    try:
        info = uav.get_raw_gps()
        res_obj = {
            "device": "uav",
            "id": str(args.sysid),
            "result": "success",
            "info": {
                "position": {
                    "lat": info.lat / 1.0e7, # to degrees
                    "lon": info.lon / 1.0e7, # to degrees
                    "alt": info.alt / 1000, # to meters
                },
                "velocity": {
                    "ground_speed": info.vel / 100, # to meters per second
                    "speed_direction": info.cog / 100 # to degrees
                },
                "satelites": info.satellites_visible
            }
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_GPS_RAW FAIL: {e}")
    return res_obj

@router.get("/ned", tags=["telemetry"], summary="Returns the copter current NED information (the information provided by this endpoint is generated by the fusion of multiple sensor data such as GPS and accelerometers)", response_model=NedTelemetryResponse, responses=COMMAND_FAILED)
def ned_info(uav: Copter = Depends(get_copter_instance), args: Namespace = Depends(get_args)):
    """Position and velocity in the local NED frame (meters and m/s, origin at
    HOME). z is negative above HOME."""
    try:
        info = uav.get_ned_info()
        res_obj = {
            "device": "uav",
            "id": str(args.sysid),
            "result": "success", 
            "info": {
            "position": {
                "x": info.x,
                "y": info.y,
                "z": info.z,
            },
            "velocity": {
                "vx": info.vx,
                "vy": info.vy,
                "vz": info.vz
            }
        }
    }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_NED_INFO FAIL: {e}")
    return res_obj

@router.get("/compass", tags=["telemetry"], summary="Returns compass calibration information", response_model=CompassTelemetryResponse, responses=error_responses({404: "No MAG_CAL_REPORT received yet — the message is only emitted during a compass calibration (never in SITL).", 500: "The underlying MAVLink command failed or timed out; detail carries the cause."}))
def compass_info(uav: Copter = Depends(get_copter_instance), args: Namespace = Depends(get_args)):
    try:
        info = uav.get_compass_info()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_COMPASS_INFO FAIL: {e}")
    if info is None:
        raise HTTPException(status_code=404, detail="No compass calibration report received (MAG_CAL_REPORT is only emitted during a compass calibration)")
    try:
        res_obj = {
            "device": "uav",
            "id": str(args.sysid),
            "result": "success",
            "info": {
                "calibration_status": info.calibration_status,
                "autosaved": bool(info.autosaved),
                "fitness": {
                    "x": info.fitness[0],
                    "y": info.fitness[1],
                    "z": info.fitness[2]
                }
            }
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_COMPASS_INFO FAIL: {e}")

    return res_obj
@router.get("/sys_status", tags=["telemetry"], summary="Returns raw SYS_STATUS message", response_model=SysStatusResponse, responses=COMMAND_FAILED)
def sys_status(uav: Copter = Depends(get_copter_instance), args: Namespace = Depends(get_args)):
    """Unprocessed SYS_STATUS as a dict; values keep MAVLink's native units
    (mV, cA, c%). Prefer /telemetry/sensor_status, /telemetry/battery_info and
    /telemetry/error_info for the parsed views."""
    try:
        status_message = uav.get_raw_status_message()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_RAW_SYS_STATUS FAIL: {e}")
    return {"device": "uav", "id": str(args.sysid), "result": "success", "status": status_message.to_dict()}

@router.get("/sensor_status", tags=["telemetry"], summary="Returns sensors status extraced from SYS_STATUS message", response_model=SensorStatusResponse, responses=COMMAND_FAILED)
def sensor_status(uav: Copter = Depends(get_copter_instance), args: Namespace = Depends(get_args)):
    """Present/enabled/health flags per sensor (gyro, accelerometer, gps,
    altitude_control, position_control, radio_receiver, motor_output, battery,
    pre_arm_check)."""
    try:
        sensor_status = uav.get_sensor_status()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_SENSOR_STATUS FAIL: {e}")
    return {"device": "uav", "id": str(args.sysid), "result": "success", "status": sensor_status}

@router.get("/battery_info", tags=["telemetry"], summary="Returns battery information extracted from SYS_STATUS message", response_model=BatteryInfoResponse, responses=COMMAND_FAILED)
def battery_info(uav: Copter = Depends(get_copter_instance), args: Namespace = Depends(get_args)):
    """Values keep MAVLink's native units: voltage in mV, current in cA (10 mA
    units, -1 if not measured), battery_remaining in percent (-1 if not
    estimated)."""
    try:
        info = uav.get_battery_info()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_BATTERY_INFO FAIL: {e}")
    return {"device": "uav", "id": str(args.sysid), "result": "success", "info": info}

@router.get("/error_info", tags=["telemetry"], summary="Returns errors information extracted from SYS_STATUS message", response_model=ErrorInfoResponse, responses=COMMAND_FAILED)
def error_info(uav: Copter = Depends(get_copter_instance), args: Namespace = Depends(get_args)):
    """Communication drop rate (c%), corrupted-packet count, and the non-zero
    autopilot error counters from SYS_STATUS."""
    try:
        info = uav.get_error_info()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_ERROR_INFO FAIL: {e}")
    return {"device": "uav", "id": str(args.sysid), "result": "success", "info": info}

@router.get("/home_info", tags=["telemetry"], summary="Returns information about HOME position, which represents the point (0,0,0) in static NED coordinate frame", response_model=HomeInfoResponse, responses=COMMAND_FAILED)
def home_info(uav: Copter = Depends(get_copter_instance), args: Namespace = Depends(get_args)):
    """Lat/lon in degrees, altitude in meters (MSL). Unlike other telemetry
    endpoints, the fields sit directly on the envelope instead of nesting
    under 'info' (historical wire contract)."""
    try:
        info = uav.get_home_position()
        res_obj = {
            "device": "uav",
            "id": str(args.sysid),
            "result": "success", 
            "lat": info["latitude"] / 1.0e7, # to degrees
            "lon": info["longitude"] / 1.0e7, # to degrees
            "altitude": info["altitude"] / 1000, # to meters
            "x": info["x"],
            "y": info["y"],
            "z": info["z"]
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GET_HOME_INFO FAIL: {e}")
    return res_obj